### ISSUE TITLE
Needs to be included in the tethys source code when scaffolding apps

### ISSUE THREAD

**Issue by waderoberts123** [rileyhales/tethysanalytics#1]
I feel as though this should be built into the Tethys source code so that users can either select the option of adding analytics when the app is scaffolded or uncomment some code when the app is scaffolded to enable the analytics.

**Comment by rileyhales** [comment]
I think most of the process thats required could be added to the app.py and base.html templates if we arrange it properly. There are basically 3 things that need to happen with the way i have it implemented right now: 1) add the line {% include analytics.html %} to base.html in the block scripts section 2) the code needs to check if the portal has installed django-analytical, 3) write the django tags that implement the tracking scripts to analytics.html.

The best way i've thought of to do it is to add a property to the app class whose value is the boolean check for whether or not the portal is set up to do tracking. Then you can include an init function to the class that contains the script that writes the django tags if that property is true and add the include tag to the base.html file. Then its entirely automated without the developer needing to do anything. it would be entirely up to the portal admin to install the django packages and set up the analytics accounts. i tested this out and i'll put it in a branch so you can look it over

**Comment by waderoberts123** [comment]
You may want to mention this in an issue in the main Tethys repo so that they could potentially get this implemented before Tethys 3.0.

**Comment by rileyhales** [comment]
Thats a good idea. I'll do that when we're ready to present about it to the Tethys scrum.

**Comment by rileyhales** [comment]
Resolved in tethys pull request 389 https://github.com/tethysplatform/tethys/pull/389
